name: bistro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_material_design_icons: ^1.1.7447
  go_router: ^16.0.0
  get_storage: ^2.1.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  flutter_multi_formatter: ^2.10.0
  country_picker: ^2.0.22
  flag: ^7.0.0
  scroll_date_picker: ^3.8.0
  cached_network_image: ^3.4.1
  http: ^1.5.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false
  image_path: assets/images/Bistro_logo.png

flutter:
  generate: true

  # Keep this true so Flutter bundles its built-in Material icon font properly.
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/fonts/Cairo/
#    - assets/fonts/Montserrat/
    # If you have a *local copy* of MaterialIcons you want to override, uncomment:
    # - assets/fonts/MaterialIcons/

  fonts:
#    - family: Fustat
#      fonts:
#        - asset: assets/fonts/Fustat/Fustat-Regular.ttf
#        - asset: assets/fonts/Fustat/Fustat-VariableFont_wght.ttf
#        - asset: assets/fonts/Fustat/Fustat-Light.ttf
#        - asset: assets/fonts/Fustat/Fustat-Medium.ttf
#        - asset: assets/fonts/Fustat/Fustat-SemiBold.ttf

#    - family: BaronNeue
#      fonts:
#        - asset: assets/fonts/BaronNeue/Baron-Neue-Black-Italic.otf
#        - asset: assets/fonts/BaronNeue/Baron-Neue-Black.otf
#        - asset: assets/fonts/BaronNeue/Baron-Neue-Bold-Italic.otf
#        - asset: assets/fonts/BaronNeue/Baron-Neue-Bold.otf
#        - asset: assets/fonts/BaronNeue/Baron-Neue-Italic.otf
#        - asset: assets/fonts/BaronNeue/Baron-Neue.otf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf


#    - family: GrandHotel
#      fonts:
#        - asset: assets/fonts/Grand_Hotel/GrandHotel-Regular.ttf
